<?php

return array(
    'epgCheck'        => array('special_video', 'home_video', 'home_large', 'home_special', 'launcher_large', 'launcher_small', 'launcher_navigation'),

    'formField'       => array(
        'text'              => 'text',
        //'file' => 'file',
        'image'             => 'image',
        //'email' => 'email',
        //'checkbox' => 'checkbox',
        //'radio' => 'radio',
        'select'            => 'select',
        //'selectRange' => 'selectRange',
        //'selectMonth' => 'selectMonth',
        'areaFilter'        => 'areaFilter',
        'ajaxInput'         => 'ajaxInput',
        'textQuick'         => 'textQuick',
        'upload2QN'         => 'upload2QN',
        'colorSelect'       => 'colorSelect',
        'formTip'           => 'formTip',
        'dateTimePicker'    => 'dateTimePicker',
        'timingState'       => 'timingState',
        'generateRandomNum' => 'generateRandomNum'
    ),

    'dataType'        => array(
        'String'    => 'String',
        'Integer'   => 'Integer',
        'Array'     => 'Array',
        'Boolean'   => 'Boolean',
        'DateTime'  => 'DateTime',
        'JsonArray' => 'JsonArray',
        'Text'      => 'Text',
        'Time'      => 'Time',
    ),

    'areaFilterList'  => array(
        1    => 'O北京',
        2    => 'P上海',
        4    => 'Q广州',
        62   => 'R深圳',
        58   => 'C杭州',
        64   => 'N宁波',
        63   => 'X厦门',
        1028 => 'J日本',
        1002 => 'M美国',
        1001 => 'Y英国',
        9999 => 'E海外其它',
        53   => 'D成都',
        999  => 'Z国内其它',
        333  => 'U未知',
        5    => 'H香港',
        34   => 'T台湾',
        6    => 'A澳门',
        7    => 'S4重庆',
        68   => 'S5苏州',
        60   => 'S6福州',
        1091 => 'S1韩国',
        1027 => 'S2新加坡',
        3    => 'V1天津',
        38   => 'V2沈阳',
        52   => 'V3南京',
        51   => 'V4长沙',
        50   => 'V5武汉',
        49   => 'V6合肥',
        46   => 'V7郑州',
        44   => 'V8西安',
        47   => 'V9济南',
        67   => 'S3无锡',
        69   => 'S7大连',
        70   => 'S8娄底',
        1011 => 'K1澳大利亚',
        1090 => 'K2新西兰',
        1086 => 'K3泰国',
        1031 => 'K4马来西亚',
        32   => 'F1广东',
        33   => 'F2福建',
        55   => 'S9昆明',
        601  => 'W旺旺'
    ),

    'areaChar2Number' => array(
        'O'  => 1,
        'P'  => 2,
        'Q'  => 4,
        'R'  => 62,
        'C'  => 58,
        'N'  => 64,
        'X'  => 63,
        'J'  => 1028,
        'M'  => 1002,
        'Y'  => 1001,
        'E'  => 9999,
        'D'  => 53,
        'Z'  => 999,
        'U'  => 333,
        'H'  => 5,
        'T'  => 34,
        'A'  => 6,
        'S4' => 7,
        'S5' => 68,
        'S6' => 60,
        'S1' => 1091,
        'S2' => 1027,
        'V1' => 3,
        'V2' => 38,
        'V3' => 52,
        'V4' => 51,
        'V5' => 50,
        'V6' => 49,
        'V7' => 46,
        'V8' => 44,
        'V9' => 47,
        'S3' => 67,
        'S7' => 69,
        'S8' => 70,
        'K1' => 1011,
        'K2' => 1090,
        'K3' => 1086,
        'K4' => 1031,
        'F1' => 32,
        'F2' => 33,
        'S9' => 55,
        'W'  => 601
    ),
);
